function enhanceStatus() {
    var enhance = document.getElementById("enhanced-button");
    enhance.classList.toggle("enhanced-enabled");

    if (document.getElementById("enhanced-text").innerHTML === "Not Enhanced") {
        document.getElementById("enhanced-text").innerHTML = "Enhanced";
        document.getElementById("jingliu-stat-img").src = "assets/IconMaxHP.png";
        document.getElementById("jingliu-stat-text").innerHTML = "HP";
        document.getElementById("jingliu-lc-1").innerHTML = "A Secret Vow";
        document.getElementById("jingliu-stat-1").innerHTML = "6.501+";
        document.getElementById("jingliu-lc-2").innerHTML = "Ninja Record: Sount The Hunt";
        document.getElementById("jingliu-stat-2").innerHTML = "7.101+";
        document.getElementById("jingliu-lc-3").style.display = "none";
        document.getElementById("jingliu-stat-3").style.display = "none";
        document.getElementById("jingliu-cdmg").innerHTML = "130%~140%+";
        document.getElementById("jingliu-atk-text").style.display = "none";
        document.getElementById("jingliu-hp-text").style.display = "list-item";
        document.getElementById("jingliu-old-cdmg").style.display = "none";
        document.getElementById("jingliu-new-cdmg").style.display = "list-item";
        document.getElementById("jingliu-chest").innerHTML = "HP";
        document.getElementById("jingliu-new-rope").innerHTML = "HP";
        document.getElementById("jingliu-ornaments").innerHTML = "Bone Collection's Serene Demesne";
        document.getElementById("jingliu-sphere").src = "assets/relics/319_0.png";
        document.getElementById("jingliu-rope").src = "assets/relics/319_1.png";
        document.getElementById("jingliu-bone").style.display = "block";
        document.getElementById("jingliu-firmament").style.display = "none";
        document.getElementById("jingliu-old-lc3").style.display = "none";
        document.getElementById("jingliu-first-lc").src = "assets/lightcones/destruction/21012.png";
        document.getElementById("jingliu-lc1-text").innerHTML = "A Secret Vow";
        document.getElementById("jingliu-lc1-text").style.right = "45px";
        document.getElementById("jingliu-vow-lc").style.display = "block";
        document.getElementById("jingliu-aeon").style.display = "none";
        document.getElementById("jingliu-lc1-dmg").innerHTML = "S5: 470.985";
        document.getElementById("jingliu-buffed-point").style.display = "list-item";
        document.getElementById("jingliu-old-point").style.display = "none";
        document.getElementById("jingliu-buff-event").style.display = "block";
        document.getElementById("jingliu-unbuff-vow").style.display = "none";
        document.getElementById("jingliu-second-lc").src = "assets/lightcones/destruction/22003.png";
        document.getElementById("jingliu-lc2-text").innerHTML = "Ninja Record: Sount The Hunt";
        document.getElementById("jingliu-lc2-text").style.right = "5px";
        document.getElementById("jingliu-lc2-dmg").innerHTML = "S5: 466.936";
        
    } else {
        document.getElementById("enhanced-text").innerHTML = "Not Enhanced";
        document.getElementById("jingliu-stat-img").src = "assets/IconAttack.png";
        document.getElementById("jingliu-stat-text").innerHTML = "ATK";
        document.getElementById("jingliu-lc-1").innerHTML = "On the Fall of An Aeon";
        document.getElementById("jingliu-stat-1").innerHTML = "2.370+";
        document.getElementById("jingliu-lc-2").innerHTML = "A Secret Vow";
        document.getElementById("jingliu-stat-2").innerHTML = "2.281+";
        document.getElementById("jingliu-lc-3").innerHTML = "Something Irrepleaceable";
        document.getElementById("jingliu-stat-3").innerHTML = "2.761+";
        document.getElementById("jingliu-lc-3").style.display = "table-cell";
        document.getElementById("jingliu-stat-3").style.display = "table-cell";
        document.getElementById("jingliu-cdmg").innerHTML = "200%+";
        document.getElementById("jingliu-atk-text").style.display = "list-item";
        document.getElementById("jingliu-hp-text").style.display = "none";
        document.getElementById("jingliu-old-cdmg").style.display = "list-item";
        document.getElementById("jingliu-new-cdmg").style.display = "none";
        document.getElementById("jingliu-chest").innerHTML = "CRIT";
        document.getElementById("jingliu-new-rope").innerHTML = "ATK";
        document.getElementById("jingliu-ornaments").innerHTML = "Firmament Frontline: Glamoth";
        document.getElementById("jingliu-sphere").src = "assets/relics/311_0.png";
        document.getElementById("jingliu-rope").src = "assets/relics/311_1.png";
        document.getElementById("jingliu-firmament").style.display = "block";
        document.getElementById("jingliu-bone").style.display = "none";
        document.getElementById("jingliu-old-lc3").style.display = "block";
        document.getElementById("jingliu-first-lc").src = "assets/lightcones/destruction/24000.png";
        document.getElementById("jingliu-lc1-text").innerHTML = "On the Fall of An Aeon";
        document.getElementById("jingliu-lc1-text").style.right = "10px";
        document.getElementById("jingliu-aeon").style.display = "block";
        document.getElementById("jingliu-vow-lc").style.display = "none";
        document.getElementById("jingliu-lc1-dmg").innerHTML = "S5: 368.534";
        document.getElementById("jingliu-old-point").style.display = "list-item";
        document.getElementById("jingliu-buffed-point").style.display = "none";
        document.getElementById("jingliu-unbuff-vow").style.display = "block";
        document.getElementById("jingliu-buff-event").style.display = "none";
        document.getElementById("jingliu-second-lc").src = "assets/lightcones/destruction/21012.png";
        document.getElementById("jingliu-lc2-text").innerHTML = "A Secret Vow";
        document.getElementById("jingliu-lc2-text").style.right = "45px";
        document.getElementById("jingliu-lc2-dmg").innerHTML = "S5: 364.492";
    }
}
